blank_issues_enabled: true
contact_links:
  - name: ğŸ ë²„ê·¸ì œë³´
    url: https://github.com/d3fau1t/web/issues/new?template=10_bug_report.md&labels=bug
    about: ë²„ê·¸ë¥¼ ë°œê²¬í•˜ì…¨ë‚˜ìš”? ì—¬ê¸°ì— ì œë³´í•´ì£¼ì„¸ìš”.
  - name: âœ¨ ê¸°ëŠ¥ ì œì•ˆ
    url: https://github.com/d3fau1t/web/issues/new?template=20_feature_request.md&labels=enhancement
    about: ìƒˆë¡œìš´ ê¸°ëŠ¥ì´ë‚˜ ê°œì„ ì‚¬í•­ì„ ì œì•ˆí•´ì£¼ì„¸ìš”.
  - name: â“ ì§ˆë¬¸í•˜ê¸°
    url: https://github.com/d3fau1t/web/issues/new?template=99_question.md&labels=question
    about: í”„ë¡œì íŠ¸ì— ëŒ€í•´ ê¶ê¸ˆí•œ ì ì´ ìˆìœ¼ì‹ ê°€ìš”?
